# Generated by Django 4.0.3 on 2022-04-01 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_url_blog_date_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 17, 3, 33, 825104)),
        ),
    ]
