# Generated by Django 4.0.3 on 2022-04-02 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 2, 13, 31, 0, 465495)),
        ),
    ]
